add real testimonial on feedbackPage
FullStackMap/Front pull request #23
Opened 2024-03-25 15:29 UTC by BaptisteLegat

2024-03-25 17:27 UTC, Dercraker requested changes

2024-03-25 17:27 UTC, Dercraker commented on src/services/BaseApi.ts
> +const basePath: string = 'http://api-dev.from-a2b.fr';
Use env var

2024-03-25 17:27 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +  });
Don't use mutation for get [React Query v5](https://tanstack.com/query/latest/docs/framework/react/quick-start)

2024-03-25 17:27 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +    };
No Try catch here... Use error handler and Notify

2024-03-25 17:27 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +  }
Replace juste carouselle and no page if Get Testimonials have some errors

2024-03-25 17:27 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +  const reviews = testimonialsMutation.data;
Export this from query

2024-03-25 17:27 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +                  <Badge bg="dark">{review.userId}</Badge>
```suggestion
                  <Badge bg="dark">{review.user.userName}</Badge>
```

2024-03-26 21:34 UTC, Baptiste-Ferrand approved these changes

2024-03-26 22:03 UTC, Dercraker requested changes

2024-03-26 22:03 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +    queryFn: AnoTestimonialsController.getAllTestimonialGET,
Await this
```suggestion
    queryFn: async () => await AnoTestimonialsController.getAllTestimonialGET,
```

2024-03-26 22:03 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +    } as NotifyDto);
Use Catch after request

2024-03-26 22:03 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +      ) : null}
Replace null by loader

2024-03-26 22:03 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +      {isError && <Text ta="center">Une erreur est survenue</Text>}
No this replace by Error Notify

2024-03-26 22:03 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
Line 127 <FormFeedback /> Disable if user is not connected

2024-03-28 21:59 UTC, Dercraker requested changes

2024-03-28 21:59 UTC, Dercraker commented on src/pages/feedback/FeedbackPage.tsx
> +    queryFn: fetchTestimonials,
Use Async func in this queryFn like this : 
```suggestion
    queryFn: async () => await machinController.TrucEndPoint(),
```

2024-03-28 21:59 UTC, Dercraker commented on src/components/feedback/FormFeedback.tsx
> +      await AnoTestimonialsController.createTestimonialAsyncPOST(id, dto),
How to save data with Authentication and Authorization with **Ano**Controller

If you save data with userLogged you must use no **Ano**Controller or you will get 401 http error

2024-03-28 22:03 UTC, Dercraker requested changes

2024-03-28 22:03 UTC, Dercraker commented on src/components/feedback/FormFeedback.tsx
>        .max(5, 'La note maximale est de 5'),
Check if the string is not Withe space

2024-03-29 15:04 UTC, Dercraker requested changes

2024-03-29 15:04 UTC, Dercraker commented on src/components/feedback/FormFeedback.tsx
> +      feedbackForm.reset();
to this in then of async func

2024-03-29 15:25 UTC, Dercraker requested changes

2024-03-29 15:25 UTC, Dercraker commented on src/components/feedback/FormFeedback.tsx
> +    },
Invalid Query Cach

2024-03-29 15:40 UTC, Dercraker approved these changes

2024-03-29 15:43 UTC, merged