Feature/home
FullStackMap/Front pull request #9
Opened 2024-03-04 09:42 UTC by BaptisteLegat

2024-03-04 11:10 UTC, Dercraker requested changes

2024-03-04 11:10 UTC, Dercraker commented on public/bg.png
Preferably svg and full name for file

2024-03-04 11:10 UTC, Dercraker commented on src/layout/header/HeaderMegaMenu.module.css
We use scss not css, don't use css files

2024-03-04 11:10 UTC, Dercraker commented on src/pages/landing/Content.tsx
> +};
One component by file not more. Move it in Component/DestinationCard.tsx

2024-03-04 11:10 UTC, Dercraker commented on src/pages/landing/Content.tsx
> +      style={{ border: hovered ? '2px solid teal' : '2px solid transparent' }}>
For this use hover with scss

2024-03-04 11:10 UTC, Dercraker commented on src/pages/landing/HeroImageBackground.module.css
We use scss not css, don't use css files

2024-03-04 11:10 UTC, Dercraker commented on src/pages/landing/LandingPage.tsx
> +    </div>
use artifact if div is not usefull

`
<>
      <HeroImageBackground />
      <Content />
</>
`

2024-03-04 11:19 UTC, Dercraker commented
you commit message must respect [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

2024-03-04 11:27 UTC, BaptisteLegat commented on src/pages/landing/LandingPage.tsx
> +    </div>
```suggestion
    <>
      <HeroImageBackground />
      <Content />
    </>
```

2024-03-05 13:44 UTC, Dercraker requested changes

2024-03-05 13:44 UTC, Dercraker commented on src/_variables.scss
> +
Useless Space

2024-03-05 13:44 UTC, Dercraker commented on src/pages/login/LoginPage.module.css
Not Css files

2024-03-05 13:44 UTC, Dercraker commented on src/pages/login/LoginPage.tsx
> +            onClick={(event) => event.preventDefault()}>
we are in typescript add type of event

2024-03-05 15:27 UTC, Dercraker approved these changes

2024-03-07 08:17 UTC, merged